config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # :users必须在devise_for后面定义 bugfix:把user当作资源的话确保路由通过devise验证
  resources :users

  get 'welcome/index'
  get 'home/profile'

  resources :contracts do
    resources :profit_ladders
  end
  resources :profit_ladders

  resources :salesman_day_tradetotals

  resource :report do
    collection do
      get :clients_days
      get :active_clients
      get :active_agents
    end
  end

  resources :notices
  resources :joinlast_clients
  resources :sales_commissions do
    collection do
      get :agents
    end
  end
  resources :bank_cards
  resources :companies
  resources :agents do
    collection do
      get :current
    end
    member do
      get :basic_info
      get :new_clients
      get :active_clients
      get :active_salesmen
    end
    resources :contracts
    resources :contacts
    resources :sales_commissions
  end
  resources :clients do
    member do
      post :tags
      get :tags
      post :note
      get :note
    end
  end
  resources :client_notes
  resources :trades
  resources :clearings
  resources :contacts
  resources :addresses
  resources :salesmen
  resources :pos_machines

  # raw data
  resources :code_tables

  root to: 'agents#current'

  # comfy_route :cms_admin, :path => '/cms-admin'
  # comfy_route :cms, :path => '/', :sitemap => false

end

app/views/client_notes/index.html.slim
p#notice
  = notice
h1
  | Listing Client Notes
table
  thead
    tr
      th
        | Note
      th
        | Type
      th[colspan="3"]
  tbody
    - @client_notes.each do |client_note|
      tr
        td
          = client_note.note
        td
          = client_note.tip
        td
          = link_to 'Show', client_note
        td
          = link_to 'Edit', edit_client_note_path(client_note)
        td
          = link_to 'Destroy', client_note, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Client note', new_client_note_path

app/views/client_notes/show.html.slim
p#notice
  = notice
p
  strong
    | Note:
  = @client_note.note
p
  strong
    | Type:
  = @client_note.tip
= link_to 'Edit', edit_client_note_path(@client_note)
|  | 
= link_to 'Back', client_notes_path