config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # :users必须在devise_for后面定义 bugfix:把user当作资源的话确保路由通过devise验证
  resources :users

  get 'welcome/index'
  get 'home/profile'

  resources :contracts do
    resources :profit_ladders
  end
  resources :profit_ladders

  resources :salesman_day_tradetotals

  resource :report do
    collection do
      get :clients_days
      get :active_clients
      get :active_agents
    end
  end

  resources :notices
  resources :joinlast_clients
  resources :sales_commissions do
    collection do
      get :agents
    end
  end
  resources :bank_cards
  resources :companies
  resources :agents do
    collection do
      get :current
    end
    member do
      get :basic_info
      get :new_clients
      get :active_clients
      get :active_salesmen
    end
    resources :contracts
    resources :contacts
    resources :sales_commissions
  end
  resources :clients do
    member do
      post :tags
      get :tags
      post :note
      get :note
    end
  end
  resources :client_notes
  resources :trades
  resources :clearings
  resources :contacts
  resources :addresses
  resources :salesmen
  resources :pos_machines

  # raw data
  resources :code_tables

  root to: 'agents#current'

  # comfy_route :cms_admin, :path => '/cms-admin'
  # comfy_route :cms, :path => '/', :sitemap => false

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :short_name)
    end
end

app/views/companies/_form.html.slim
= form_for(@company) do |f|
  - if @company.errors.any?
    #error_explanation
      h2
        = pluralize(@company.errors.count, "error")
        |  prohibited this company from being saved:
      ul
        - @company.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :name
    br
    = f.text_area :name
  .field
    = f.label :short_name
    br
    = f.text_field :short_name
  .actions
    = f.submit

app/views/companies/edit.html.slim
h1
  | Editing Company
= render 'form'
= link_to 'Show', @company
|  | 
= link_to 'Back', companies_path

app/views/companies/index.html.slim
p#notice
  = notice
h1
  | Listing Companies
table
  thead
    tr
      th
        | Name
      th
        | Short name
      th[colspan="3"]
  tbody
    - @companies.each do |company|
      tr
        td
          = company.name
        td
          = company.short_name
        td
          = link_to 'Show', company
        td
          = link_to 'Edit', edit_company_path(company)
        td
          = link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Company', new_company_path

app/views/companies/new.html.slim
h1
  | New Company
= render 'form'
= link_to 'Back', companies_path

app/views/companies/show.html.slim
p#notice
  = notice
p
  strong
    | Name:
  = @company.name
p
  strong
    | Short name:
  = @company.short_name
= link_to 'Edit', edit_company_path(@company)
|  | 
= link_to 'Back', companies_path