config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # :users必须在devise_for后面定义 bugfix:把user当作资源的话确保路由通过devise验证
  resources :users

  get 'welcome/index'
  get 'home/profile'

  resources :contracts do
    resources :profit_ladders
  end
  resources :profit_ladders

  resources :salesman_day_tradetotals

  resource :report do
    collection do
      get :clients_days
      get :active_clients
      get :active_agents
    end
  end

  resources :notices
  resources :joinlast_clients
  resources :sales_commissions do
    collection do
      get :agents
    end
  end
  resources :bank_cards
  resources :companies
  resources :agents do
    collection do
      get :current
    end
    member do
      get :basic_info
      get :new_clients
      get :active_clients
      get :active_salesmen
    end
    resources :contracts
    resources :contacts
    resources :sales_commissions
  end
  resources :clients do
    member do
      post :tags
      get :tags
      post :note
      get :note
    end
  end
  resources :client_notes
  resources :trades
  resources :clearings
  resources :contacts
  resources :addresses
  resources :salesmen
  resources :pos_machines

  # raw data
  resources :code_tables

  root to: 'agents#current'

  # comfy_route :cms_admin, :path => '/cms-admin'
  # comfy_route :cms, :path => '/', :sitemap => false

end

app/controllers/bank_cards_controller.rb
class BankCardsController < ApplicationController
  before_action :set_bank_card, only: [:show, :edit, :update, :destroy]

  # GET /bank_cards
  # GET /bank_cards.json
  def index
    @bank_cards = BankCard.all
  end

  # GET /bank_cards/1
  # GET /bank_cards/1.json
  def show
  end

  # GET /bank_cards/new
  def new
    @bank_card = BankCard.new
  end

  # GET /bank_cards/1/edit
  def edit
  end

  # POST /bank_cards
  # POST /bank_cards.json
  def create
    @bank_card = BankCard.new(bank_card_params)

    respond_to do |format|
      if @bank_card.save
        format.html { redirect_to @bank_card, notice: 'Bank card was successfully created.' }
        format.json { render :show, status: :created, location: @bank_card }
      else
        format.html { render :new }
        format.json { render json: @bank_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bank_cards/1
  # PATCH/PUT /bank_cards/1.json
  def update
    respond_to do |format|
      if @bank_card.update(bank_card_params)
        format.html { redirect_to @bank_card, notice: 'Bank card was successfully updated.' }
        format.json { render :show, status: :ok, location: @bank_card }
      else
        format.html { render :edit }
        format.json { render json: @bank_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bank_cards/1
  # DELETE /bank_cards/1.json
  def destroy
    @bank_card.destroy
    respond_to do |format|
      format.html { redirect_to bank_cards_url, notice: 'Bank card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank_card
      @bank_card = BankCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_card_params
      params.require(:bank_card).permit(:bank_name, :bank_sub_branch, :account_name, :account_number)
    end
end

app/views/bank_cards/index.html.slim
p#notice
  = notice
h1
  | Listing Bank Cards
table
  thead
    tr
      th
        | Bank name
      th
        | Bank sub branch
      th
        | Account name
      th
        | Account number
      th[colspan="3"]
  tbody
    - @bank_cards.each do |bank_card|
      tr
        td
          = bank_card.bank_name
        td
          = bank_card.bank_sub_branch
        td
          = bank_card.account_name
        td
          = bank_card.account_number
        td
          = link_to 'Show', bank_card
        td
          = link_to 'Edit', edit_bank_card_path(bank_card)
        td
          = link_to 'Destroy', bank_card, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to 'New Bank card', new_bank_card_path

app/views/bank_cards/show.html.slim
p#notice
  = notice
p
  strong
    | Bank name:
  = @bank_card.bank_name
p
  strong
    | Bank sub branch:
  = @bank_card.bank_sub_branch
p
  strong
    | Account name:
  = @bank_card.account_name
p
  strong
    | Account number:
  = @bank_card.account_number
= link_to 'Edit', edit_bank_card_path(@bank_card)
|  | 
= link_to 'Back', bank_cards_path