config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # :users必须在devise_for后面定义 bugfix:把user当作资源的话确保路由通过devise验证
  resources :users

  get 'welcome/index'
  get 'home/profile'

  resources :contracts do
    resources :profit_ladders
  end
  resources :profit_ladders

  resources :salesman_day_tradetotals

  resource :report do
    collection do
      get :clients_days
      get :active_clients
      get :active_agents
    end
  end

  resources :notices
  resources :joinlast_clients
  resources :sales_commissions do
    collection do
      get :agents
    end
  end
  resources :bank_cards
  resources :companies
  resources :agents do
    collection do
      get :current
    end
    member do
      get :basic_info
      get :new_clients
      get :active_clients
      get :active_salesmen
    end
    resources :contracts
    resources :contacts
    resources :sales_commissions
  end
  resources :clients do
    member do
      post :tags
      get :tags
      post :note
      get :note
    end
  end
  resources :client_notes
  resources :trades
  resources :clearings
  resources :contacts
  resources :addresses
  resources :salesmen
  resources :pos_machines

  # raw data
  resources :code_tables

  root to: 'agents#current'

  # comfy_route :cms_admin, :path => '/cms-admin'
  # comfy_route :cms, :path => '/', :sitemap => false

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def clients_days
    year = params[:q][0..3].to_i
    month = params[:q][5..7].to_i
    dt = Date.new(year, month, 1)
    @prev_month = dt - 1.month
    @next_month = dt + 1.month
    @collection = ClientDayTradetotal.select(%Q(
    trade_date,
    sum(total_amount) as total_amount,
    sum(total_count) as total_count,
    sum(wechat_amount) as wechat_amount,
    sum(wechat_count) as wechat_count,
    sum(alipay_amount) as alipay_amount,
    sum(alipay_count) as alipay_count,
    sum(t0_amount) as t0_amount,
    sum(t0_count) as t0_count,
    sum(t1_amount) as t1_amount,
    sum(t1_count) as t1_count
    )).where(trade_date: dt.all_month).group(:trade_date).order("trade_date ASC")

    keys = ['total_amount', 'total_count', 'wechat_amount', 'wechat_count', 'alipay_amount', 'alipay_count', 't0_amount', 't0_count' ]

    tmp = ClientDayTradetotal.where("trade_date"=>dt.all_month)
    @total_sums = {}
    keys.each do |k|
      @total_sums[k] = tmp.sum(k).to_f
    end

  end

  def new_clients
    @collection = Client.order("join_date DESC").take(10)
  end

  def active_clients
    year = params[:q][0..3].to_i
    month = params[:q][5..7].to_i
    dt = Date.new(year, month, 1)
    @collection_clients = []
    idx = 0
    all = Biz::SysTotalBiz.active_clients(dt, 'total_amount')
    all.each do |t|
      idx += 1
      client = Client.find(t["client_id"])
      c = client.contacts.first
      # total = Biz::AgentTotalBiz.new(client.id)
      t["idx"] = idx
      if c
        t["contact_name"] = c.name || ''
        t["contact_tel"] = c.tel || ''
      end
      # # t['cooperation_type'] = agent.cooperation_type_id
      # t['cooperation_date'] = agent.cooperation_date
      # t["salesman_count"] = total.salesman_all.count
      # t["client_count"] = total.clients_all.count
      # t["client_new_count"] = total.new_clients.count

      t["location"] = ''
      @collection_clients << t
    end
  end

  def active_agents
    year = params[:q][0..3].to_i
    month = params[:q][5..7].to_i
    dt = Date.new(year, month, 1)
    @collection_agents = []
    idx = 0
    all = Biz::SysTotalBiz.active_agents(dt, 'total_amount')
    all.each do |t|
      idx += 1
      agent = Agent.find(t["agent_id"])
      c = agent.contacts.first
      total = Biz::AgentTotalBiz.new(agent.id)
      t["idx"] = idx
      if c
        t["contact_name"] = c.name || ''
        t["contact_tel"] = c.tel || ''
      end
      t['cooperation_type'] = agent.cooperation_type_id
      t['cooperation_date'] = agent.cooperation_date
      t["salesman_count"] = total.salesman_all.count
      t["client_count"] = total.clients_all.count
      t["client_new_count"] = total.new_clients.count

      t["location"] = ''
      @collection_agents << t
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def trade_value(objs, trade_type, attr)
    obj = objs.find{|t| t.trade_type == trade_type}
    if obj && obj.has_attribute?(attr)
      if attr == :amount
        n2 obj[attr]
      else
        n0 obj[attr]
      end
    else
      nil
    end
  end

  def trade_sum_month(trade_month, trade_type, field)
    ts = TradeSum.where(sum_obj_type: 'ALL', sum_type: 'month', trade_date: trade_month, trade_type: trade_type).first
    ts[field] if ts
  end
end

app/views/reports/_active_agents_report.html.slim
table.table
  thead
    tr
      th 排名
      th 渠道名称
      th 联系人
      th 手机
      th 合作时间
      th 业务数
      th 累计户
      th 当月户
      th 总金额
      th 微金额
      th 微笔数
      th 支金额
      th T0金额
      th 操作
  tbody
    - @collection_agents.each do |r|
      tr
        td= r["idx"]
        / td= r["name"]
        td= r["contact_name"]
        td= r["contact_tel"]
        td= r["cooperation_type"]
        td= r["cooperation_date"]
        td= r["salesman_count"]
        td= r["client_count"]
        td= r["client_new_count"]
        / 
        / td= r['salesman.count']
        / td= r['clienter.count']
        / td= r["clienter.new"]
        / 
        td= r["total_amount"]
        td= r["wechat_amount"]
        td= r["wechat_count"]
        td= r["alipay_amount"]
        td= r["t0_amount"]
        td= r["t0_count"]
        
        
        

app/views/reports/_active_clients_report.html.slim
table.table
  thead
    tr
      th 排名
      th 商户名称
      th 联系人
      th 手机
      th 地区
      th 业务员
      th 渠道
      th 入网时间
      th 费率
      th 总金额
      th 微金额
      th 微笔数
      th 支金额
      th 支笔数
      th T0金额
      th T0笔数
  tbody
    - @collection_clients.each do |r|
      tr
        td= r["idx"]
        td= r["shop_name"]
        td= r["contact_name"]
        th= r["contact_tel"]
        td= r["location"]
        td= link_to(r["salesman.name"], r["salesman.url"])
        td= r["qudao"]
        td= r['join_date']
        th= r["rate"]
        td= r["total_amount"]
        td= r["wechat_amount"]
        td= r["wechat_count"]
        td= r["alipay_amount"]
        td= r["alipay_count"]
        td= r["t0_amount"]
        td= r["t0_count"]
    

app/views/reports/_clients_days_summary.html.slim
table.table
  thead
    tr
      th 日期
      th 总交易
      th 总笔数
      th 微金额
      th 微笔数
      th 支金额
      th 支笔数
      th T0金额
      th T0笔数
  tbody
    - @collection.each do |r|
      tr
        td= r.trade_date.day
        td= r.total_amount
        td= r.total_count
        td= r.wechat_amount
        td= r.wechat_count
        td= r.alipay_amount
        td= r.alipay_count
        td= r.t0_amount
        td= r.t0_count
    /
    /汇总信息
    tr 
      td 汇总
      td #{@total_sums["total_amount"]}
      td #{@total_sums["total_count"]}
      td #{@total_sums["wechat_amount"]}
      td #{@total_sums["wechat_count"]}
      td #{@total_sums["alipay_amount"]}
      td #{@total_sums["alipay_count"]}
      td #{@total_sums["t0_amount"]}
      td #{@total_sums["t0_count"]}
          

app/views/reports/_new_clients_report.html.slim
table.table
  thead
    tr
      th 商户名称
      th 手机      
      th 业务员
      
      th 费率
      th 入网时间
      th 操作
  tbody
    - @collection.each do |r|
      tr
        td= r.shop_name
        td= r.shop_tel
        td= link_to(r.salesman.name, salesman_path(r.salesman))
        td= r.rate
        td= r.join_date
        th= link_to('操作', client_path(r))

app/views/reports/active_agents.js.erb
$('#active_agents')
  .html("<%=j render 'active_agents_report' %>");

app/views/reports/active_clients.js.erb
$('#active_clients')
  .html("<%=j render 'active_clients_report' %>");

app/views/reports/clients_days.html.slim
= render 'clients_days_summary'

app/views/reports/clients_days.js.erb
$('#mon_trades_total')
  .html("<%=j render 'clients_days_summary' %>");

$('#mon_trades_title').text("<%= params[:q] %>");
$('#mon_trades_prev').unbind('click').click(function(){
  $.getScript("<%= clients_days_report_path(q: @prev_month.strftime('%Y-%m')) %>");
});
$('#mon_trades_next').unbind('click').click(function(){
  $.getScript("<%= clients_days_report_path(q: @next_month.strftime('%Y-%m')) %>");
});

app/views/reports/new_clients.js.erb
$('#new_clients')
  .html("<%=j render 'new_clients_report' %>");